# Fix API Gateway Security Headers
# This adds HSTS, CSP, etc. to all 4xx/5xx responses generated by API Gateway

$ApiId = "zcrqexrdw1" # Your API ID
$Region = "us-east-1"

Write-Host "Configuring Gateway Responses for API: $ApiId..."

# Define headers to add
# Note: Values must be single-quoted inside the string for AWS CLI
$Headers = "gatewayresponse.header.Strict-Transport-Security='max-age=31536000; includeSubDomains',gatewayresponse.header.X-Content-Type-Options='nosniff',gatewayresponse.header.X-Frame-Options='DENY',gatewayresponse.header.Content-Security-Policy='default-src ''self'''"

# Response types to update
$ResponseTypes = @("DEFAULT_4XX", "DEFAULT_5XX", "ACCESS_DENIED", "UNAUTHORIZED", "THROTTLED")

foreach ($Type in $ResponseTypes) {
    Write-Host "Updating $Type..."
    
    aws apigateway put-gateway-response `
        --rest-api-id $ApiId `
        --response-type $Type `
        --response-parameters $Headers `
        --region $Region
}

Write-Host "Deploying changes to Prod stage..."
aws apigateway create-deployment `
    --rest-api-id $ApiId `
    --stage-name "Prod" `
    --region $Region

Write-Host "✅ API Gateway Headers Configured Successfully!"
