AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MeDUSA Backend API - API v3 Compliant (100% Tested)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.10
    Environment:
      Variables:
        # Encoding Configuration
        PYTHONIOENCODING: 'utf-8'
        LC_ALL: 'C.UTF-8'
        LANG: 'C.UTF-8'
        
        # JWT Configuration
        JWT_SECRET: '{{resolve:secretsmanager:medusa/jwt:SecretString:secret}}'
        JWT_EXPIRE_SECONDS: '3600'
        REFRESH_TTL_SECONDS: '604800'
        
        # Database Configuration
        DDB_TABLE_USERS: !Ref UsersTable
        DDB_TABLE_REFRESH: !Ref RefreshTokensTable
        DDB_TABLE_POSES: !Ref PosesTable
        DDB_TABLE_DEVICES: !Ref DevicesTable
        DDB_TABLE_PATIENT_PROFILES: !Ref PatientProfilesTable
        DDB_TABLE_SESSIONS: !Ref SessionsTable
        DDB_TABLE_TREMOR_ANALYSIS: medusa-tremor-analysis
        
        # Storage Configuration
        S3_BUCKET: !Ref DataBucket
        
        # Email Configuration (AWS SES)
        USE_SES: 'true'  # Enable real email sending via AWS SES
        SENDER_EMAIL: 'zsun54@jh.edu'  # Verified email address
        SES_REGION: 'us-east-1'  # SES region (AWS_REGION is auto-provided by Lambda)
        
        # Environment
        ENVIRONMENT: 'production'
        USE_MEMORY: 'false'  # Use real AWS services in production
    Architectures:
      - x86_64

Resources:
  # Lambda Function
  MedusaAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: medusa-api-v3
      CodeUri: backend-py/
      Handler: main.handler
      Description: MeDUSA API v3 - 100% Tested
      Policies:
        # DynamoDB Access Permissions
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PosesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RefreshTokensTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientProfilesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-tremor-analysis"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-tremor-analysis/index/*"
        # S3 Access Permissions
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        # AWS SES Email Sending Permissions
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: '*'
      Events:
        # API Gateway Events
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MedusaAPI
      Tags:
        Project: MeDUSA
        Version: v3
        Status: Production

  # API Gateway
  MedusaAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: medusa-api-v3
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,Authorization,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers'"
        AllowOrigin: "'*'"  # Replace with specific domain in production
        MaxAge: "'600'"
        AllowCredentials: false
      Auth:
        DefaultAuthorizer: NONE  # Using application-layer middleware authentication
      TracingEnabled: true
      Tags:
        Project: MeDUSA
        Version: v3

  # DynamoDB Table - Users
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-users-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Users

  # DynamoDB Table - Poses
  PosesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-poses-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Poses

  # DynamoDB Table - Refresh Tokens
  RefreshTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-refresh-tokens-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiresAt
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: RefreshTokens

  # DynamoDB Table - Devices
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-devices-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: macAddress
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: macAddress-index
          KeySchema:
            - AttributeName: macAddress
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Devices

  # DynamoDB Table - Patient Profiles
  PatientProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-patient-profiles-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: doctorId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: doctorId-index
          KeySchema:
            - AttributeName: doctorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: PatientProfiles

  # DynamoDB Table - Device Sessions (Dynamic Binding)
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-sessions-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: deviceId-index
          KeySchema:
            - AttributeName: deviceId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: patientId-index
          KeySchema:
            - AttributeName: patientId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Sessions

  # S3 Storage Bucket
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'medusa-data-prod-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'  # Replace with specific domain in production
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3

  # Process Sensor Data Function
  ProcessSensorDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: medusa-process-sensor-data
      CodeUri: process-data-lambda/
      Handler: process_sensor_data.lambda_handler
      Description: Process sensor data to extract tremor features
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-sensor-data"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-sensor-data/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-tremor-analysis"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-tremor-analysis/index/*"
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
      Events:
        SensorDataStream:
          Type: DynamoDB
          Properties:
            Stream: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/medusa-sensor-data/stream/2026-02-03T02:51:28.000"
            StartingPosition: LATEST
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
            Enabled: True

  # WAFv2 Web ACL
  MedusaWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${AWS::StackName}-WebACL"
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${AWS::StackName}-WebACL"
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 10
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationList

  # WAF Association
  MedusaWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn: MedusaAPIProdStage
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${MedusaAPI}/stages/Prod"
      WebACLArn: !GetAtt MedusaWebACL.Arn

Outputs:
  # API Gateway URL
  ApiUrl:
    Description: "MeDUSA API Gateway endpoint URL"
    Value: !Sub "https://${MedusaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: MedusaApiUrl
  
  # Lambda Function ARN
  FunctionArn:
    Description: "MeDUSA Lambda Function ARN"
    Value: !GetAtt MedusaAPIFunction.Arn
    Export:
      Name: MedusaFunctionArn
  
  # DynamoDB Tables
  UsersTableName:
    Description: "Users DynamoDB Table Name"
    Value: !Ref UsersTable
    Export:
      Name: MedusaUsersTable
  
  PosesTableName:
    Description: "Poses DynamoDB Table Name"
    Value: !Ref PosesTable
    Export:
      Name: MedusaPosesTable
  
  # S3 Bucket
  DataBucketName:
    Description: "Data S3 Bucket Name"
    Value: !Ref DataBucket
    Export:
      Name: MedusaDataBucket
  
  # API Documentation
  SwaggerUI:
    Description: "API Documentation (after deployment)"
    Value: !Sub "https://${MedusaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/docs"

