AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MeDUSA Backend API - API v3 Compliant (100% Tested)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.10
    Environment:
      Variables:
        # Encoding Configuration
        PYTHONIOENCODING: 'utf-8'
        LC_ALL: 'C.UTF-8'
        LANG: 'C.UTF-8'
        
        # JWT Configuration
        JWT_SECRET: '{{resolve:secretsmanager:medusa/jwt:SecretString:secret}}'
        JWT_EXPIRE_SECONDS: '3600'
        REFRESH_TTL_SECONDS: '604800'
        
        # Database Configuration
        DDB_TABLE_USERS: !Ref UsersTable
        DDB_TABLE_REFRESH: !Ref RefreshTokensTable
        DDB_TABLE_POSES: !Ref PosesTable
        
        # Storage Configuration
        S3_BUCKET: !Ref DataBucket
        
        # Environment
        ENVIRONMENT: 'production'
        USE_MEMORY: 'false'  # Use real AWS services in production
    Architectures:
      - x86_64

Resources:
  # Lambda 函数
  MedusaAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: medusa-api-v3
      CodeUri: backend-py/
      Handler: main.handler
      Description: MeDUSA API v3 - 100% Tested
      Policies:
        # DynamoDB 访问权限
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PosesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RefreshTokensTable
        # S3 访问权限
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        # API Gateway 事件
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MedusaAPI
      Tags:
        Project: MeDUSA
        Version: v3
        Status: Production

  # API Gateway
  MedusaAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: medusa-api-v3
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"  # 生产环境改为具体域名
      Auth:
        DefaultAuthorizer: NONE  # 使用应用层中间件认证
      TracingEnabled: true
      Tags:
        Project: MeDUSA
        Version: v3

  # DynamoDB 表 - 用户
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-users-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Users

  # DynamoDB 表 - Poses
  PosesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-poses-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: Poses

  # DynamoDB 表 - Refresh Tokens
  RefreshTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: medusa-refresh-tokens-prod
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expiresAt
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3
        - Key: DataType
          Value: RefreshTokens

  # S3 存储桶
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'medusa-data-prod-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'  # 生产环境改为具体域名
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Project
          Value: MeDUSA
        - Key: Version
          Value: v3

Outputs:
  # API Gateway URL
  ApiUrl:
    Description: "MeDUSA API Gateway endpoint URL"
    Value: !Sub "https://${MedusaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: MedusaApiUrl
  
  # Lambda Function ARN
  FunctionArn:
    Description: "MeDUSA Lambda Function ARN"
    Value: !GetAtt MedusaAPIFunction.Arn
    Export:
      Name: MedusaFunctionArn
  
  # DynamoDB Tables
  UsersTableName:
    Description: "Users DynamoDB Table Name"
    Value: !Ref UsersTable
    Export:
      Name: MedusaUsersTable
  
  PosesTableName:
    Description: "Poses DynamoDB Table Name"
    Value: !Ref PosesTable
    Export:
      Name: MedusaPosesTable
  
  # S3 Bucket
  DataBucketName:
    Description: "Data S3 Bucket Name"
    Value: !Ref DataBucket
    Export:
      Name: MedusaDataBucket
  
  # API Documentation
  SwaggerUI:
    Description: "API Documentation (after deployment)"
    Value: !Sub "https://${MedusaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/docs"

